networks:
    yt-info-api.network:
        driver: bridge


services:
    yt-info-api:
        build:
            context: ./youtubeijs-info-api
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: on-failure

        ports:
            - "127.0.0.1:8080:8080"
            
        networks:
            - "yt-info-api.network"